name: Compare Fork

on:
  workflow_dispatch:
    inputs:
      fork_url:
        description: 'Fork URL to compare with'
        required: true
        default: 'https://github.com/planetoftheorg/react-in-action-from-setup-to-deployment-5972102'

jobs:
  compare-fork:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Extract fork information
      id: extract_fork_info
      run: |
        echo "Fork URL: ${{ github.event.inputs.fork_url }}"
        # Extract owner and repo from the fork URL
        FORK_OWNER=$(echo "${{ github.event.inputs.fork_url }}" | awk -F '/' '{print $4}')
        FORK_REPO=$(echo "${{ github.event.inputs.fork_url }}" | awk -F '/' '{print $5}')
        echo "fork_owner=$FORK_OWNER" >> $GITHUB_ENV
        echo "fork_repo=$FORK_REPO" >> $GITHUB_ENV

    - name: Fetch changes between main branch and fork
      id: fetch_changes
      run: |
        BASE_BRANCH="main"
        FORK_BRANCH="main"
        FORK_OWNER=${{ env.fork_owner }}
        FORK_REPO=${{ env.fork_repo }}
        git remote add fork https://github.com/$FORK_OWNER/$FORK_REPO.git
        git fetch fork $FORK_BRANCH
        CHANGES=$(git diff origin/$BASE_BRANCH...fork/$FORK_BRANCH --name-only)
        echo "changes=$CHANGES" >> $GITHUB_ENV

    - name: Generate document using AI
      id: generate_document
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Reference the secret here
      run: |
        CHANGES=${{ env.changes }}
        PROMPT=$(cat <<-END
          Pretend the changes haven't been done and write a document that asks someone to make the changes as part of a capstone document. I don't need the actual changes, just the document describing what needs to be done.

          Here are the changes:
          $CHANGES

          I don't need the code. Just a summary of what sort of changes the student might make. Keep it short and make the explanations simple for a beginner audience.

          At the end, add a short list of other suggestions, but don't show any code. Assume that the student is a beginner, Junior Developer, so make the changes simple and something a beginner might do.
          END
        )
        RESPONSE=$(curl -X POST "https://api.openai.com/v1/engines/davinci-codex/completions" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $OPENAI_API_KEY" \
          -d '{
            "prompt": "'"$PROMPT"'",
            "max_tokens": 500
          }')
        echo "response=$RESPONSE" >> $GITHUB_ENV

    - name: Save document
      run: |
        echo "${{ env.response }}" > CAPSTONE_DOCUMENT.md
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add CAPSTONE_DOCUMENT.md
        git commit -m "Add generated capstone document"
        git push
